// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Subject.BussinesLayout.Data;

#nullable disable

namespace Subject.BussinesLayout.Migrations
{
    [DbContext(typeof(SchoolSubjectContext))]
    [Migration("20221008143555_AddedSchoolProfessors")]
    partial class AddedSchoolProfessors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Subject.Domain.SchoolSubjectModel.Literature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiteratureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolSubjectId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolSubjectId");

                    b.ToTable("Literature", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Chris McMullen",
                            LiteratureName = "Essential Calculus Skills Practice Workbook with Full Solutions",
                            SchoolSubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Chris McMullen",
                            LiteratureName = "Algebra Essentials Practice Workbook with Answers: Linear & Quadratic Equations, Cross Multiplying, and Systems of Equations: Improve Your Math Fluency Series",
                            SchoolSubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Oxford",
                            LiteratureName = "Oxford Advanced Learner’s Dictionary (OALD)",
                            SchoolSubjectId = 2
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "3dtotal Publishing",
                            LiteratureName = "Artists’ Master Series: Color and Light",
                            SchoolSubjectId = 3
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Victor Perard",
                            LiteratureName = "Anatomy and Drawing (Dover Art Instruction)",
                            SchoolSubjectId = 3
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Robert D. Kaplan",
                            LiteratureName = "Adriatic: A Concert of Civilizations at the End of the Modern Age",
                            SchoolSubjectId = 4
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Edward Hallett Carr",
                            LiteratureName = "What Is History?",
                            SchoolSubjectId = 5
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Charles C. Mann",
                            LiteratureName = "1491",
                            SchoolSubjectId = 5
                        },
                        new
                        {
                            Id = 9,
                            AuthorName = "Asaad Almohammad",
                            LiteratureName = "An Ishmael of Syria (Paperback)",
                            SchoolSubjectId = 6
                        },
                        new
                        {
                            Id = 10,
                            AuthorName = "Alex Michaelides",
                            LiteratureName = "The Silent Patient (Hardcover)",
                            SchoolSubjectId = 6
                        });
                });

            modelBuilder.Entity("Subject.Domain.SchoolSubjectModel.Professors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessorDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearsOfExpirience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Professors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Johnny",
                            LastName = "Depp",
                            ProfessorDescription = "Teach one or more university subjects to undergraduate and graduate students. Prepare and deliver lectures to students and conduct laboratory sessions or discussion groups. Prepare, administer and grade examinations, laboratory assignments and reports. Advise students on course and academic matters and career decisions.",
                            YearsOfExpirience = 15
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jessica",
                            LastName = "Alba",
                            ProfessorDescription = "Teach one or more university subjects to undergraduate and graduate students. Prepare and deliver lectures to students and conduct laboratory sessions or discussion groups. Prepare, administer and grade examinations, laboratory assignments and reports. Advise students on course and academic matters and career decisions.",
                            YearsOfExpirience = 12
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Angelina",
                            LastName = "Joly",
                            ProfessorDescription = "Teach one or more university subjects to undergraduate and graduate students. Prepare and deliver lectures to students and conduct laboratory sessions or discussion groups. Prepare, administer and grade examinations, laboratory assignments and reports. Advise students on course and academic matters and career decisions.",
                            YearsOfExpirience = 30
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Luise",
                            LastName = "Armstrong",
                            ProfessorDescription = "Teach one or more university subjects to undergraduate and graduate students. Prepare and deliver lectures to students and conduct laboratory sessions or discussion groups. Prepare, administer and grade examinations, laboratory assignments and reports. Advise students on course and academic matters and career decisions.",
                            YearsOfExpirience = 24
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Tony",
                            LastName = "Montana",
                            ProfessorDescription = "Teach one or more university subjects to undergraduate and graduate students. Prepare and deliver lectures to students and conduct laboratory sessions or discussion groups. Prepare, administer and grade examinations, laboratory assignments and reports. Advise students on course and academic matters and career decisions.",
                            YearsOfExpirience = 32
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Tonny",
                            LastName = "Stark",
                            ProfessorDescription = "Teach one or more university subjects to undergraduate and graduate students. Prepare and deliver lectures to students and conduct laboratory sessions or discussion groups. Prepare, administer and grade examinations, laboratory assignments and reports. Advise students on course and academic matters and career decisions.",
                            YearsOfExpirience = 15
                        });
                });

            modelBuilder.Entity("Subject.Domain.SchoolSubjectModel.SchoolSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfWeeklyClasses")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SchoolSubject", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mathematics is the science and study of quality, structure, space, and change. Mathematicians seek out patterns, formulate new conjectures, and establish truth by rigorous deduction from appropriately chosen axioms and definitions.",
                            NumberOfWeeklyClasses = 3,
                            SubjectName = "Math"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The subject shall help build up general language proficiency through listening,speaking,reading and writing,and provide the opportunity to acquire information and specialised knowledge through the English language.",
                            NumberOfWeeklyClasses = 3,
                            SubjectName = "English"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The term subjects in art refers to the main idea that is represented in the artwork. The subject in art is basically the essence of the piece. To determine subject matter in a particular piece of art, ask yourself: What is actually depicted in this artwork?",
                            NumberOfWeeklyClasses = 2,
                            SubjectName = "Art"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Geography is the study of places and the relationships between people and their environments. Geographers explore both the physical properties of Earth's surface and the human societies spread across it.",
                            NumberOfWeeklyClasses = 2,
                            SubjectName = "Geography"
                        },
                        new
                        {
                            Id = 5,
                            Description = "History is the study of life in society in the past, in all its aspect, in relation to present developments and future hopes. It is the story of man in time, an inquiry into the past based on evidence. Indeed, evidence is the raw material of history teaching and learning.",
                            NumberOfWeeklyClasses = 4,
                            SubjectName = "History"
                        },
                        new
                        {
                            Id = 6,
                            Description = "This course is a study of theory and research of the normal personality including basic concepts, techniques of measurement, and relevant findings. This course surveys the major theories of personality, including trait, psychodynamic, humanistic, cognitive, and behavioral perspectives.",
                            NumberOfWeeklyClasses = 2,
                            SubjectName = "Psychology"
                        });
                });

            modelBuilder.Entity("Subject.Domain.SchoolSubjectModel.SubjectProfesors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectProfesors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProfessorId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProfessorId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProfessorId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 4,
                            ProfessorId = 6,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 5,
                            ProfessorId = 6,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 6,
                            ProfessorId = 5,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 7,
                            ProfessorId = 3,
                            SubjectId = 5
                        });
                });

            modelBuilder.Entity("Subject.Domain.SchoolSubjectModel.Literature", b =>
                {
                    b.HasOne("Subject.Domain.SchoolSubjectModel.SchoolSubject", "SchoolSubject")
                        .WithMany("Literature")
                        .HasForeignKey("SchoolSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolSubject");
                });

            modelBuilder.Entity("Subject.Domain.SchoolSubjectModel.SubjectProfesors", b =>
                {
                    b.HasOne("Subject.Domain.SchoolSubjectModel.Professors", "Professor")
                        .WithMany("SubjectProfesors")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Subject.Domain.SchoolSubjectModel.SchoolSubject", "Subject")
                        .WithMany("SubjectProfesors")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Subject.Domain.SchoolSubjectModel.Professors", b =>
                {
                    b.Navigation("SubjectProfesors");
                });

            modelBuilder.Entity("Subject.Domain.SchoolSubjectModel.SchoolSubject", b =>
                {
                    b.Navigation("Literature");

                    b.Navigation("SubjectProfesors");
                });
#pragma warning restore 612, 618
        }
    }
}
